# Generated by Django 2.1.7 on 2019-03-28 14:23

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastralInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('[0-9]{2}:[0-9]{2}:[0-9]{7}:[0-9]{1,10}', 'Invalid cadastral number')])),
                ('loading_state', models.PositiveSmallIntegerField(choices=[(0, 'not loaded'), (1, 'loaded'), (2, 'failed')], default=0)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
