# Generated by Django 2.1.7 on 2019-04-01 14:50

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastral', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastralinfo',
            name='cadastral_number',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('[0-9]{2}:[0-9]{2}:[0-9]{1,7}:[0-9]{1,10}', 'Invalid cadastral number')]),
        ),
        migrations.AlterField(
            model_name='cadastralinfo',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(null=True),
        ),
    ]
