from datetime import timedelta
import os


EMAIL_SENDING_TIMEOUT = timedelta(seconds=30)

CADASTRAL_INFO_TIMEOUT_DELAY = 60
CADASTRAL_API_TIMEOUT = 10

WEATHER_API_KEY = '570cabc13dca49dab1295355190104'
WEATHER_API_TIMEOUT = 10
WEATHER_HISTORY_DAYS_IN_BULK = 30
WEATHER_HISTORY_COUNT_BULKS = 3

SCIHUB_LOGIN = 'profx5'
SCIHUB_PASSWORD = '06YN6WnO'
SENTINEL_PRODUCTS_DAYS_PAST = 10
SENTINEL_MAX_CLOUD_PERCENTAGE = 30
SENTINEL_PRODUCTS_DOWNLOAD_PATH = '/tmp/agronom/'
NDVI_UPSCALE_FACTOR = 10
