# Generated by Django 2.1.7 on 2019-03-28 14:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
                ('centroid', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('name', models.CharField(default='My field', max_length=100)),
                ('cadastral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastral.CadastralInfo')),
            ],
        ),
    ]
