# Generated by Django 2.1.7 on 2019-03-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='color',
            field=models.CharField(default='#333777', max_length=7),
        ),
        migrations.AddField(
            model_name='field',
            name='crop_type',
            field=models.CharField(default='Wheat', max_length=100),
        ),
    ]
