# Generated by Django 2.1.7 on 2019-04-10 14:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0002_auto_20190328_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('state', models.PositiveSmallIntegerField(choices=[(0, 'done'), (1, 'not done')])),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.Field')),
                ('name', models.CharField(max_length=100))
            ],
        ),
    ]
