# Generated by Django 2.1.7 on 2019-03-28 14:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.Field')),
            ],
        ),
    ]
