# Generated by Django 2.1.7 on 2019-04-02 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weather',
            options={'ordering': ('-date',)},
        ),
    ]
