# Generated by Django 2.1.7 on 2019-04-02 14:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fields', '0002_auto_20190328_1906'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDVI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('img', models.ImageField(upload_to='')),
                ('mean', models.DecimalField(decimal_places=2, max_digits=3)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fields.Field')),
                ('product_id', models.CharField(db_index=True, max_length=100)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPointField(default=None))
            ],
        ),
    ]
