# Generated by Django 2.1.7 on 2019-04-09 15:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ndvi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ndvi',
            name='boundary',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
        ),
    ]
